spring.application.name=ProjectManagement

spring.datasource.url=jdbc:mysql://localhost:3306/projectManagementSystem
spring.datasource.username=root
spring.datasource.password=Ar@20051125
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smpt.gmail.com
spring.mail.port=587
spring.mail.username=aryan.shrivastav2005@gmail.com
spring.mail.password=aryanaryan25
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.smtp.starttls.enable=true

razorpay.api.key=rzp_test_5NYr5rWRBwIjeJddf4m
razorpay.api.secret=iwY4bd3C4bkK8Ft45fg782ZAHJZ80